version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: event_notifier_redis
    ports:
      - "6379:6379"
    restart: "no"

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: event_notifier_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: "no"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'